### PR TITLE
config-helper tool reintroduced to help with the initial configuration

### PR DESCRIPTION
**Pull request by misncz**
Not sure why it was removed but I added it back and modified so that it's working with the new API .... in case you'd find it handy @fdegier

### CODE REVIEW

**Comment by misncz** [comment]
Also if you accept it then remove the logging of the requests in debug mode ... I personally would log them using another settings

**Review by fdegier — APPROVED** [review]
Thanks @misncz

**Comment by fdegier** [comment]
Thanks for all your work @misncz send me your PayPal so I can buy you a coffee / beer 😄

**Comment by fdegier** [comment]
I think the reason why it was removed is because for a while I hosted this https://github.com/fdegier/Homebridge-Jablotron-Congig-helper

**Comment by misncz** [comment]
> Thanks for all your work @misncz send me your PayPal so I can buy you a coffee / beer 😄

Don't worry really - I do it for myself too ;-)

**Pull request merged**
